### ISSUE TITLE
Das Update ist fehlgeschlagen 8.0.2 > 8.0.3

### ISSUE THREAD

**Issue by Xandersoft** [owncloud/updater#119] opened 2015-05-10 09:44 UTC
Das Update ist fehlgeschlagen. Bitte überprüfe die Protokolle auf der Administratorenseite

Debug 	updater 	Downloaded 29420896 bytes. 

Whats wrong?

**Comment by RealRancor** [comment] 2015-05-10 12:22
Hi,

please check the logfiles (admin gui or /data/owncloud.log) as advised. Without the informations from the logfiles its just a guessing game whats wrong here.

**Comment by RealRancor** [comment] 2015-05-12 07:50
@Xandersoft Ping?

**Comment by VicDeo** [comment] 2015-05-25 14:33
@Xandersoft please provide webserver error log  and owncloud.log excerpts as requested.
I suspect this is a duplicate of https://github.com/owncloud/updater/issues/86
and you need to follow these steps: https://github.com/owncloud/updater/issues/86#issuecomment-99187323

**Comment by radistmorse** [comment] 2015-06-05 09:22
Same here. Tried the solution from #86 (comment the line in finalize () ), and the error changed to

Call to undefined function OCA\Updater\Location\first() in /usr/share/nginx/html/apps/updater/lib/location/apps.php on line 44

After I changed
```php
$pathData = first(\OC::$APPSROOTS);
```
to
```php
$pathData = \OC::$APPSROOTS[0];
```
everything seemed to work OK. I'm doing "occ upgrade" right now, but do not expect any troubles.

**Comment by VicDeo** [comment] 2015-06-08 16:32
@radistmorse solution with commenting the line is incomplete.
I posted the link to the fix right above your message.

**Comment by VicDeo** [comment] 2015-06-09 19:03
@Xandersoft closing due to lack of data. Feel free to reopen providing log file entries after unsuccessful updated attempt

**Closed by VicDeo** 2015-06-09 19:03 UTC
Labels: needs info

**Comment by Xandersoft** [comment] 2015-06-21 19:00
Sorry, I gave it up to update and works with the 8.02, but testing with new installations 8.03 and 8.04 which dont work succesfully with android-app.
The logfiles was all to big ... 15 or 20 GBytes becouse of an error in tempmanager.php (no access to /tmp folder)

**Comment by VicDeo** [comment] 2015-06-30 16:29
@Xandersoft you can use logrotate or shipped with OC rotation capability https://github.com/owncloud/core/blob/stable8/config/config.sample.php#L517

The entire log file is not needed. Just a few recent entries after an unsuccessful update attempt.
