### ISSUE TITLE
"cURL error 51" on running web updater

### ISSUE THREAD

**Issue by bcutter** [owncloud/updater#414] opened 2016-12-11 16:29 UTC
Hi,

at the very beginning (still in the "Initializing" part) on a v9.1.1 I receive:

```
[GuzzleHttp\Exception\RequestException]
cURL error 51: SSL: no alternative certificate subject name matches target host name 'hostname' 

[GuzzleHttp\Exception\RequestException]
cURL error 51: SSL: no alternative certificate subject name matches target host name 'hostname' 
```

I remind a few days ago the owncloud app store had some issues with new Let´s Encrypt certificates.
Is this one related to this issue?

**Comment by bcutter** [comment] 2016-12-11 17:04
Update:
1) Above mentioned error appears when using the internal address of the OC instance/server.
2) When using the external address (with a valid SSL certificate), I get:

```
[UnexpectedValueException]
Could not parse a response for config:list. Please check if the current shell user can run occ command. Raw output:
Not allowed
```

What the... is wrong here???

**Comment by bcutter** [comment] 2016-12-11 18:31
Update:
After applying the patch from https://central.owncloud.org/t/patches-for-known-update-issues-from-version-9-0-4-9-0-5-9-1-0-9-1-1/3549, I receive the following error when using the external address (with a valid SSL certificate):

```
cURL error 51: SSL: no alternative certificate subject name matches target host name 'localhost' 
```

This time on a white page, no updater frame (I guess that explicitly changed because of the applied patch).

**Comment by bcutter** [comment] 2016-12-11 18:41
Oh folks I´m so freaked out on this whole update thing. And I don´t even know if it´s OwnCloud related. Hope to get some response here from experts.

**Comment by PVince81** [comment] 2016-12-12 08:02
Ok, some background info about the updater: the web updater doesn't use any code from ownCloud core. So it communicates with ownCloud core using HTTP calls. It looks like in your environment these calls fail due to certificate reasons, so the updater cannot communicate with core for this reason and is not able to retrieve the config:list for example.

@VicDeo can you assist ?

**Comment by VicDeo** [comment] 2016-12-12 19:14
@bcutter what' your cUrl and openssl versions?

**Comment by VicDeo** [comment] 2016-12-12 19:26
@bcutter 
the most obvious reason is that your server is using SSL and your environment has none of the following environment variables set:
`$_SERVER['HTTP_X_FORWARDED_HOST']`
`$_SERVER['HTTP_HOST']`
`$_SERVER['SERVER_NAME']`

in that case updater tries to connect to your ownCloud via the URL `https://localhost`

**Comment by bcutter** [comment] 2016-12-12 19:28
```
OpenSSL 1.0.1t  3 May 2016
```
```
curl 7.38.0 (arm-unknown-linux-gnueabihf) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP
```

**Comment by bcutter** [comment] 2016-12-12 19:33
Puh, so how/where can I check if this is the case for me?

I´m really scared cause nothing (besides regular package updates like MySQL server, don´t think there was a Nginx update too since update to v9.1.1) changed on the affected system... can you please point me to the right direction? I think those env var´s need to come from nginx right?

**Comment by bcutter** [comment] 2016-12-12 19:38
**Update:** part of nginx config below, SERVER_NAME is set:

```
server {
  listen                                80;
  server_name                           internal external.com internal.fritz.box;
  #rewrite                              ^ https://$server_name$request_uri? permanent; # enforce https
}

server {
  listen                                443 ssl;
  server_name                           internal external.com internal.fritz.box;
```

**Comment by VicDeo** [comment] 2016-12-12 19:40
@bcutter IIRC for nginx $_SERVER['SERVER_NAME'] should match one used in 
`server_name` nginx directive.
Can you check phpinfo output for this host? 
just upload a temporary file
info.php
```
<?php 
phpinfo();
```
open it from browser and search for HTTP_HOST on the page

**Comment by bcutter** [comment] 2016-12-12 19:42
```
_SERVER["HTTP_HOST"]	internal
```

Looking good so far.

**Comment by VicDeo** [comment] 2016-12-12 19:48
@bcutter Did you use `internal` as a domain to open updater page (when the cURL error happened)?
I guess it is accessible via http?

**Comment by VicDeo** [comment] 2016-12-12 19:52
@bcutter 
Updater respects the current  protocol so if it is possible you can open it via http to avoid SSL errors.

**Comment by bcutter** [comment] 2016-12-12 19:52
Of course I did, URL giving the CURL error 51 is:
https://internal/owncloud/index.php/settings/admin#updater

But when using external address (https://external.com/owncloud/index.php/settings/admin#updater) error looks like this:
```
cURL error 51: SSL: no alternative certificate subject name matches target host name 'localhost' 
```

**Comment by bcutter** [comment] 2016-12-12 19:55
I have a rewrite rule (as posted [here](https://github.com/owncloud/updater/issues/414#issuecomment-266530049) 16 minutes ago), no HTTP allowed. And I definitely don´t want to "temporarily" allow HTTP for update purposes... that would be a step back, wouldn´t it :-(

**Comment by bcutter** [comment] 2016-12-12 20:06
I think maybe there was a change at the local Let´s Encrypt environment. Will check logs (last renewal a few days ago) and report back. Feels a bit like fishing for the last straw, but I don´t want you to waste your time when in the end it is a fault of mine.

**By the way (relevant?):** Because 9.1.1 still has a bug in the web updater, I needed to remove/comment those part of nginx site config, otherwise nothint will happen when pushing updater button:
```
# Musste am 2016-08-15, 2016-10-29 und 2016-12-11 auskommentiert werden, damit ein Update von OwnCloud überhaupt möglich war, siehe https://github.com/owncloud/core/issues/25551#issuecomment-239778960
#  location ~ ^/owncloud/(?:updater|ocs-provider)(?:$|/) {
#    try_files                          $uri $uri/ =404;
#    index                              index.php;
#  }
```

**Comment by VicDeo** [comment] 2016-12-12 20:07
@bcutter I haven't suggested to dispose SSL, your redirect rule just seems to be commented.
I assume that `internal` has a valid SSL certificate?

**Comment by bcutter** [comment] 2016-12-12 20:10
No, external.com has a valid Let´s Encrypt certificate (and doesn´t work either). "internal" is manually trusted in the browser trying to run the updater. Didn´t matter in the past.

**Comment by bcutter** [comment] 2016-12-12 20:13
Update to LE cert renewal: Just a warning (":WARNING:certbot.cli:You are running with an old copy of letsencrypt-auto that does not receive updates, and is...", "certbot version: 0.9.3") in the logs, but everything went fine.

**Comment by VicDeo** [comment] 2016-12-12 20:15
@bcutter it used to spawn a new PHP process before, but now it connects to your ownCloud with cURL.

You can just run updater  from CLI as an option:
`sudo -u www-data php updater/application.php`

**Comment by bcutter** [comment] 2016-12-12 21:13
Hmm, that looks interesting. But why isn´t it documented @ https://doc.owncloud.org/server/9.1/admin_manual/configuration_server/occ_command.html?

And am I willing doing updates by a CLI command (which would be a workaround) instead of trying to solve the issue (which would be a solution)...

OK you named two workarounds already (comment http rewrite rule, use undocumented CLI command), thank you very much for this so far.

But... how can I come to a solution for the root source of this issue?

**Comment by bcutter** [comment] 2016-12-14 18:26
Any remaining ideas?

**Comment by VicDeo** [comment] 2016-12-15 15:36
@bcutter if you would like to debug it to the very end I prepare some additional logging soon

**Comment by bcutter** [comment] 2016-12-15 18:49
Yes, some way I feel like "I wanna try fix that". The web updater app always provided (and nowadays does this better then ever) a very convenient way for updating, even if a SSH access is possible. So I´m willing to put in a little more time.

**Comment by bcutter** [comment] 2016-12-17 16:48
Found some documentation on the CLI options of the updater app. Will dive into it and give it a try. v9.1.3 already is out and I´m still stuck on 9.1.1, lil bit frustrating.

**Comment by bcutter** [comment] 2016-12-17 18:47
I´m happy with the CLI of the updater app. A little "bad feeling" is left anyway because of the root source of this issue. But the CLI workaround is OK for me.

**Comment by VicDeo** [comment] 2017-02-02 22:57
@bcutter 
ok, I was able to reproduce something similar.

1. the first request is going with a correct domain. It is blocked because origin is not localhost 
2. the second request is a fallback to https://localhost (causing cUrl error 51 in UI)

But in my case it was resolved with applying https://github.com/owncloud/core/commit/82cd86a2079c515df5889648c828c29e51424dab#diff-1b29c3a8398e3ed87e772fb50a729633

**Closed by VicDeo** 2017-02-02 22:57 UTC

**Comment by berezovskyi** [comment] 2017-03-11 22:37
I was updating from 8.x and one of the versions I had to go through was 9.0.6.5.

I hit the same issue with `_SERVER["SERVER_NAME"]` and `_SERVER["HTTP_HOST"]` set to the right domain name and `curl -I https://blablabla.com` working well.

`sudo -u www-data php updater/application.php` updated my installation to 9.1.2 without any problems.

**Comment by IMEIICCID** [comment] 2017-06-17 12:23
Hi I also got problems updating from ownCloud 9.0.9 to ownCloud 9.0.10 !
last time I could solve this problem by open Owncloud via "https://192.168.1.4/ownlcoud" instead of my LetsEncrypt Domain.

Updating via https://LetsEncrypt-Domain.de/owncloud  (valid Certificate)
Error is:  cURL error 51: SSL: no alternative certificate subject name matches target host name 'localhost' 

sudo -u www-data php updater/application.php  gives me an error
sudo: unknown user: www-data
sudo: unable to initialize policy plugin

I'm using Synology maybe thats why.

Any Idea?

**Comment by vanthoi** [comment] 2017-07-08 06:34
nginx @IMEIICCID  ?
run command: sudo -u apache php updater/application.php for centos

**Comment by guruz** [comment] 2017-08-01 10:05
I'm also getting this when trying to update my 10.0.0 :[
```
cURL error 51: SSL: no alternative certificate subject name matches target host name 'localhost'
```

@VicDeo why does the updater connect to localhost?

**Comment by guruz** [comment] 2017-08-02 11:51
Patch for the localhost error message by @VicDeo in https://github.com/owncloud/updater/pull/434
