### ISSUE TITLE
Updater Button does not work in 9.0.2

### ISSUE THREAD

**Issue by kgulti** [owncloud/updater#396] opened 2016-10-12 05:45 UTC
Hey guys today I wanted to update from version 9.0.2 to 9.0.4 with the updater from the admin section. But the button doesn't work, it has no function. Already try to disable the asset pipeline that causes errors in version 8.x.x but the button won't open the updater.

Thank you very much.

**Comment by VicDeo** [comment] 2016-10-13 21:10
@kgulti What's your PHP version?

**Comment by kgulti** [comment] 2016-10-14 05:21
@VicDeo I'm running on PHP 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1 (cli)

**Comment by kgulti** [comment] 2016-10-24 07:40
So far I've no idea how I can solve the problem. Hope somebody has an idea, only want to update.

**Comment by RealRancor** [comment] 2016-11-03 18:51
Might be a duplicate of https://github.com/owncloud/core/issues/25551

@kgulti If you want to update just do the manual update without the updater app like explained here:

https://doc.owncloud.org/server/latest/admin_manual/maintenance/manual_upgrade.html

**Comment by VicDeo** [comment] 2016-12-12 20:10
@kgulti are you using nginx?

**Comment by kgulti** [comment] 2016-12-13 10:15
@VicDeo yes running on nginx

**Comment by VicDeo** [comment] 2018-05-03 07:56
Closing as 9.0 is EOL. Feel free to join discussion in https://github.com/owncloud/updater/issues/453 where exactly the same issue is tracked.
Please also note that you might need to update your nginx config according to https://github.com/owncloud/documentation/pull/2551

**Closed by VicDeo** 2018-05-03 07:56 UTC
