### ISSUE TITLE
Error updating from 8.0.2 to 8.0.3.

### ISSUE THREAD

**Issue by MarcosAM** [owncloud/updater#125] opened 2015-05-17 22:22 UTC
Hi!
The automatic updater, on the Replace stage (number 3), returned the error:

The update was unsuccessful. Please check logs at admin page and report this issue to the ownCloud community.

My server log show:
[fcgid:warn] [pid 17497] [client 179.92.216.240:59589] mod_fcgid: stderr: PHP Fatal error:  Cannot redeclare class OC\\Security\\SecureRandom in /home/xpto/owncloud/lib/private/security/securerandom.php on line 24, referer: https://www.xpto.org/owncloud/index.php/apps/updater/update.php

System: CentOS 7
Server: Apache/2.4.6 (CentOS)
PHP: 5.4.16 (cli) (built: Oct 31 2014 12:59:36)

Thanks in advance.

Best regards

**Comment by RealRancor** [comment] 2015-05-18 06:36
Hi,

duplicate of: https://github.com/owncloud/updater/issues/86 , https://github.com/owncloud/updater/issues/93 , https://github.com/owncloud/updater/issues/99 , https://github.com/owncloud/updater/issues/98 , https://github.com/owncloud/updater/issues/88

In the first issue you can find a possible workaround at https://github.com/owncloud/updater/issues/86#issuecomment-78503941

**Closed** 2015-05-18 06:38 UTC

**Comment by VicDeo** [comment] 2015-05-18 13:28
@MarcosAM I'd suggest the following solution instead:
https://github.com/owncloud/updater/issues/86#issuecomment-99187323
