### ISSUE TITLE
No backup files listed 

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/updater#197] opened 2015-11-25 07:23 UTC
@peterkahl reported in [core](https://github.com/owncloud/core/issues/20721):

> OS 8.2.1 shows no backups, although they exist in the exact same directory.
![no-backups](https://cloud.githubusercontent.com/assets/2703373/11387410/1f863590-9365-11e5-887e-9514cdaf9bd5.png)

**Comment by VicDeo** [comment] 2015-12-02 16:13
might be related to #184

**Comment by VicDeo** [comment] 2016-02-17 12:58
@peterkahl is it still reproducible?

**Comment by peterkahl** [comment] 2016-02-17 22:34
Related to #184. Since I dsabled the setting described in #184, the issue has gone.

**Comment by VicDeo** [comment] 2016-02-17 22:38
@peterkahl thanks, than  https://github.com/owncloud/updater/issues/184 should fix it regardless the `pipeline` option state

**Comment by VicDeo** [comment] 2016-02-17 22:39
oops I mean https://github.com/owncloud/updater/pull/198

**Comment by peterkahl** [comment] 2016-02-17 22:51
My version is 8.2.2, so I need to try re-enabling the pipeline setting. Thanks!

**Comment by VicDeo** [comment] 2016-02-17 23:59
@peterkahl please let me know if it works now

**Comment by peterkahl** [comment] 2016-02-21 00:10
Yes. I have set
```
'asset-pipeline.enabled' => true
```
and verified that the backup files are listed now with OC 8.2.2.2.
Thanks.

**Comment by VicDeo** [comment] 2016-02-23 16:04
Thanks, closing then

**Closed by VicDeo** 2016-02-23 16:04 UTC
