### ISSUE TITLE
Updater Button does not work

### ISSUE THREAD

**Issue by bah0071** [owncloud/updater#453] opened 2017-12-27 15:44 UTC
updater 10.0.3.3 
it shows that update 10.0.4 is available but when i click on "open updater" it does not open a new window...

is there a way to force open the updater app?

**Comment by VicDeo** [comment] 2017-12-28 20:02
@bah0071 is anything logged into owncloud.log after "open updater" is clicked?
you can open updater by adding /upater to your ownCloud  URL 
`your.domain.tld/updater` or something like this

**Comment by VicDeo** [comment] 2017-12-28 20:33
The other thing: you'll need to generate access token manually accordance with this instructions https://doc.owncloud.org/server/10.0/admin_manual/maintenance/update.html#updater-secret-value-in-config-php to access the updater page by a direct url

**Comment by VicDeo** [comment] 2019-10-08 13:04
Closing as there has been no feedback for 22 months.
Feel free to reopen if the issue is still reproducible with 10.1 and above

**Closed** 2019-10-08 13:04 UTC
