### ISSUE TITLE
Updater for 10.x does not check PHP version

### ISSUE THREAD

**Issue by stkjj** [owncloud/updater#444] opened 2017-10-03 16:45 UTC
running an update from 9.1.2 to 10.0.3 on a Ubuntu 14.04 with PHP 5.5.9 failed because updater started, run into trouble and finished with an installation saying "update your PHP version to 5.6.0".

After the update 10.0.3 was incomplete showing that files from /updater didn't pass integrity check (e.g. still where 9.1.2 versions). 

Pls add a routine to check PHP version in advance, to avoid this hassle.

**Comment by kdslkdsaldsal** [comment] 2017-10-04 06:27
Closing as a duplicate of https://github.com/owncloud/updater/issues/356

**Closed by kdslkdsaldsal** 2017-10-04 06:27 UTC
