### ISSUE TITLE
Updater is not copying over ca-bundle.crt?

### ISSUE THREAD

**Issue by RealRancor** [owncloud/updater#164] opened 2015-08-14 08:30 UTC
Hi,

i'm not using the updater so i can't reproduce this but i have now read from three different people that they used the updater to go from 8.0.5 to 8.1.1 (https://github.com/owncloud/core/issues/17448#issuecomment-130879981) and afterwards the config/ca-bundle.crt was missing.

Anyone could try to reproduce this to avoid issues with failed connections to the appstore and similar problems.

**Comment by LukasReschke** [comment] 2015-08-14 15:04
Ok. That's the source why we have all the bug reports in core. Great.

We shall add an hard requirement in core and next time ensure proper testing. Thanks. 

cc @karlitschek

**Comment by LukasReschke** [comment] 2015-08-14 15:05
This breaks a lot. Awesome … :rocket:

**Comment by LukasReschke** [comment] 2015-08-14 15:07
https://github.com/owncloud/updater/commit/d9b8f19b2ec11df47159532d8259ffe8d85eb0e9 

We really need some logic check that ensures that the current updater is even able to update to the next version…

**Comment by karlitschek** [comment] 2015-08-14 18:49
Hmmm. Actually our documentation says that you can keep the config folder as is. That a bundle needs to be copied is not exactly intuitive or error prove. 
@VicDeo Can we fix that?

**Comment by LukasReschke** [comment] 2015-08-14 19:39
It's not only that bundle. - That folder is used for other purposes as well such as mimetype mappings,

That said, there is already a "fix" for this. What the problem is that the updater is just delivering updates for versions it is not capable of which will explode hard.

**Comment by LukasReschke** [comment] 2015-08-14 19:47
Also related to https://github.com/owncloud/core/issues/18309 - would make _everything_ way more stable.

**Comment by RealRancor** [comment] 2015-08-14 20:35
@LukasReschke Its not sure that the updater isn't copy over the bundle. I'm just guessing after the reports linked above and at forum/irc. This still needs to be verified.

**Comment by LukasReschke** [comment] 2015-08-15 10:18
> @LukasReschke Its not sure that the updater isn't copy over the bundle. I'm just guessing after the reports linked above and at forum/irc. This still needs to be verified.

It doesn't. At least not when coming from 8.0.5. Which I did on my instance :-)

**Comment by RealRancor** [comment] 2015-08-15 10:26
Ah, sure. The files.json of the updater shipped with 8.0.5 doesn't contain the bundle:

https://github.com/owncloud/updater/blob/stable8/lib/files.json

**Comment by tech4eleven** [comment] 2015-09-18 19:38
I just tried to update via the updater in the admin section. I had 8.0.x and wanted to update to current 8.1.3. Getting a message that says:

Updating ownCloud to version 8.1.3, this may take a while.
Turned on maintenance mode
Exception: Please upload the ca-bundle.crt file into the 'config' directory.
The update was unsuccessful. Please report this issue to the ownCloud community.

What can I do? http://cloud.tech4eleven.com

**Comment by RealRancor** [comment] 2015-09-18 19:44
This:

> Please upload the ca-bundle.crt file into the 'config' directory.

**Comment by VicDeo** [comment] 2015-09-18 19:45
Avalable here https://github.com/owncloud/core/tree/master/config

**Comment by tech4eleven** [comment] 2015-09-18 19:49
right after i posted this i figured i could try to download the own cloud zip from the website and copy over the crt file. so literally just did that and it worked. thanks all.

**Comment by MALPI** [comment] 2015-09-22 04:32
Actually after putting the zip file manually there, the upgrade process was stuck. I had to put the new binaries manually into the installation also, run occ upgrade. Still OC didn't leave maintenance mode. After setting the flag manually to `false` OC was at least able to start again. 

Last but not least, the gallery App didn't work anymore, I had to replace it by gallery+. It crashed with a `NoRoute...Exception` by symfony.

Overall this upgrade was really painfull!

**Comment by karlitschek** [comment] 2015-09-22 11:05
@LukasReschke where are we with moving the bundle to /core ? Can't find the pr at the moment.

**Comment by LukasReschke** [comment] 2015-09-22 12:50
At the "people discussing about mimetype and whatever" state… https://github.com/owncloud/core/pull/18893 :speak_no_evil:

**Comment by LukasReschke** [comment] 2015-09-23 07:54
Merged. So now we need to ensure that the updater copies the new folder :see_no_evil: 

cc @VicDeo

**Comment by 23d-conception** [comment] 2015-09-23 20:25
Hello,
Not sure it's the good solution, but I have solve it simply with add an empty ca-bundle.crt file in config folder ;)

**Comment by RealRancor** [comment] 2015-09-23 20:28
Thats definitely the worst solution. Instead follow the instructions some posts above describing where to get a valid ca-bundle.crt.

**Comment by janusbenissa** [comment] 2015-10-19 07:54
Sorry but try to update and get this error, try to find the file but it is not in the master/config ?

**Comment by RealRancor** [comment] 2015-10-19 08:00
@janusbenissa For master it got moved to: https://raw.githubusercontent.com/owncloud/core/master/resources/config/ca-bundle.crt with the PR https://github.com/owncloud/core/pull/18893

**Comment by janusbenissa** [comment] 2015-10-19 08:32
Thanks for the answer
But sorry i'm not a programmer and I was  expect a download link so that I can upload it into the config directory (i can't make a crt file with notepad ++ otherwise I make it myself)

"Exception: Please upload the ca-bundle.crt file into the 'config' directory."

**Comment by RealRancor** [comment] 2015-10-19 08:34
This is a download-link. Open https://raw.githubusercontent.com/owncloud/core/master/resources/config/ca-bundle.crt, save-page as -> save to config dir

**Comment by janusbenissa** [comment] 2015-10-19 08:51
Oke,, I know I was missing something :-)
Thanks, everything works now and I can use version 8.1.3

**Comment by euneuber** [comment] 2015-10-24 12:31
don't forget to make ca-bundle.crt readable to your web server ;-)

**Comment by RealRancor** [comment] 2015-10-24 12:53
Which should be really obvious :)

**Comment by Kissaki** [comment] 2015-10-25 18:26
Where should the file be coming from?
I checked the github repository master config folder which was linked above, with no such file.
I then downloaded 8.2.0, which does not have such a file either.
While a direct link to a ca-bundle.crt was linked above, its user content. (You can obviously check the user accounts association with owncloud, but this whole mess is less than ideal.)

**Comment by Kissaki** [comment] 2015-10-25 18:46
The file does exist in the 8.1.3 version package.

**Comment by RealRancor** [comment] 2015-10-25 19:15
@Kissaki For oC 8.2.0 this is not needed anymore. The file is placed within the /resources/config and is already copied over if you do a correct upgrade.

**Comment by PVince81** [comment] 2016-07-20 12:57
Also happening when updating from 8.0.14 to 8.1.9 (using a test update server),
I can see that the file "ca-bundle.crt" does exist in the tarball, but the updater app from 8.0 doesn't seem to copy it properly.

CC @davitol

**Comment by PVince81** [comment] 2016-07-20 12:58
@VicDeo is there anything we can do with the old updater code to make it at least process this file correctly ?

**Comment by PVince81** [comment] 2016-08-16 15:56
it will here https://github.com/owncloud/updater/issues/367

**Closed** 2016-09-13 08:50 UTC
Labels: sev1-critical
