### ISSUE TITLE
Update to 8.0.4 failed

### ISSUE THREAD

**Issue by bergymen** [owncloud/updater#159] opened 2015-07-24 21:43 UTC
I was unable to update my owncloud as I got these errors..

[{"reqId":"edc3e5972444785d8ac228f19ccbde16","remoteAddr":"64.229.165.201","app":"PHP","message":"Only variables should be passed by reference at \/home\/progteam\/public_html\/owncloud\/lib\/private\/cache\/fileglobalgc.php#50","level":3,"time":"2015-07-24T20:50:38+00:00","method":"GET","url":"\/cron.php"},{"reqId":"2b83ae44502c115e74c447455cf934fa","remoteAddr":"64.229.165.201","app":"PHP","message":"Cannot redeclare class OC\\Security\\SecureRandom at \/home\/progteam\/public_html\/owncloud\/lib\/private\/security\/securerandom.php#24","level":3,"time":"2015-07-24T20:42:42+00:00","method":"POST","url":"\/index.php\/apps\/updater\/ajax\/update.php"},

Can someone help?
thanks

**Comment by RealRancor** [comment] 2015-07-25 11:45
Duplicate of https://github.com/owncloud/updater/issues/86 (and a lot of others reported here) where you can find a workaround here: https://github.com/owncloud/updater/issues/86#issuecomment-99187323

**Closed** 2015-07-25 12:08 UTC

**Comment by bergymen** [comment] 2015-07-25 15:31
Thank you verry much it worked !
