### ISSUE TITLE
"Error PHP Array to string conversion"

### ISSUE THREAD

**Issue by terokorp** [owncloud/updater#193] opened 2015-11-22 05:28 UTC
at file https://github.com/owncloud/updater/blob/master/controller/admincontroller.php#L52 $feed['versionstring'] is empty array and suposed to be string. That causing PHP error at https://github.com/owncloud/core/blob/master/lib/private/template/functions.php#L36
( caled at https://github.com/owncloud/updater/blob/master/templates/admin.php#L23 )

ownCloud 8.2.1 (stable)

**Comment by terokorp** [comment] 2015-11-22 05:29
Maybe related to #184

**Comment by VicDeo** [comment] 2016-02-16 19:06
Closing as a duplicate of https://github.com/owncloud/updater/issues/133

**Closed by VicDeo** 2016-02-16 19:06 UTC
