### ISSUE TITLE
App directory not deleted during update

### ISSUE THREAD

**Issue by tflidd** [owncloud/updater#168] opened 2015-08-29 22:56 UTC
### Steps to reproduce
1. Take OC 8.0.4, use mail app.
2. Update to OC 8.1.1 using the updater app
3. Install manually the ca-bundle.crt (https://github.com/owncloud/updater/issues/164)
4. Try to activate a 3rd-party app that has been updated since

### Expected behaviour
Should download and install the new version.

### Actual behaviour
Error shows up: "App directory already exists". This is true, but it is read- and writeable to the webserver user, so it could have been deleted. The apps directory:
````
1053991 4.0K drwxrwxrwx 24 www-data www-data 4.0K Aug 29 22:31 .
1052650 4.0K drwxr-xr-x 13 www-data www-data 4.0K Aug 29 22:31 ..
1122446 4.0K drwxr-xr-x 12 www-data www-data 4.0K Aug 29 22:31 activity
1122365 4.0K drwxr-xr-x 14 www-data www-data 4.0K Aug 29 22:31 encryption
1122309 4.0K drwxr-xr-x 10 www-data www-data 4.0K Aug 29 22:31 external
1122387 4.0K drwxr-xr-x 14 www-data www-data 4.0K Aug 29 22:31 files
1447692 4.0K drwxr-xr-x 14 www-data www-data 4.0K Jun  4 13:43 files_encryption
1114285 4.0K drwxr-xr-x 14 www-data www-data 4.0K Aug 29 22:31 files_external
1114484 4.0K drwxr-xr-x  6 www-data www-data 4.0K Aug 29 22:31 files_locking
1114515 4.0K drwxr-xr-x  9 www-data www-data 4.0K Aug 29 22:31 files_pdfviewer
1114490 4.0K drwxr-xr-x 12 www-data www-data 4.0K Aug 29 22:31 files_sharing
1122462 4.0K drwxr-xr-x  9 www-data www-data 4.0K Aug 29 22:31 files_texteditor
1122428 4.0K drwxr-xr-x 12 www-data www-data 4.0K Aug 29 22:31 files_trashbin
1114512 4.0K drwxr-xr-x 11 www-data www-data 4.0K Aug 29 22:31 files_versions
1122417 4.0K drwxr-xr-x  7 www-data www-data 4.0K Aug 29 22:31 files_videoviewer
1114270 4.0K drwxr-xr-x 10 www-data www-data 4.0K Aug 29 22:31 firstrunwizard
1114511 4.0K drwxr-xr-x  9 www-data www-data 4.0K Aug 29 22:31 gallery
1582759 4.0K drwxr-xr-x 10 www-data www-data 4.0K Jun 19 13:03 mail
1114514 4.0K drwxr-xr-x  6 www-data www-data 4.0K Aug 29 22:31 provisioning_api
1114472 4.0K drwxr-xr-x 12 www-data www-data 4.0K Aug 29 22:31 templateeditor
1114513 4.0K drwxr-xr-x 11 www-data www-data 4.0K Aug 29 22:31 updater
1122350 4.0K drwxr-xr-x  6 www-data www-data 4.0K Aug 29 22:31 user_external
1122318 4.0K drwxr-xr-x 13 www-data www-data 4.0K Aug 29 22:31 user_ldap
1114280 4.0K drwxr-xr-x  6 www-data www-data 4.0K Aug 29 22:31 user_webdavauth
````
Manual deletion of the mail-folder solved the issue.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** Mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.1.1

**Updated from an older ownCloud or fresh install:** 8.0.4

**List of activated apps:**

```
 - activity: 2.0.1
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
```

**The content of config/config.php:**

```
<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => 'ocmr3ngu09p3',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'myhost',
  ),
  'datadirectory' => '/var/www/oc8/owncloud/data',
  'overwrite.cli.url' => 'https://myhost/oc8/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'octtoc8',
  'dbhost' => 'localhost:/var/run/mysqld/mysqld.sock',
  'dbtableprefix' => '',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'xxx',
  'installed' => true,
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### ownCloud log (data/owncloud.log)
```
{"reqId":"qD7+5690V1lNtCtAaZlS","remoteAddr":"ip","app":"core","message":"No update found at the ownCloud appstore for app 166055","level":1,"time":"2015-08-29T22:38:48+00:00","method":"GET","url":"\/oc8\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"qD7+5690V1lNtCtAaZlS","remoteAddr":"ip","app":"core","message":"No update found at the ownCloud appstore for app 166056","level":1,"time":"2015-08-29T22:38:48+00:00","method":"GET","url":"\/oc8\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"qD7+5690V1lNtCtAaZlS","remoteAddr":"ip","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":1,"time":"2015-08-29T22:38:48+00:00","method":"GET","url":"\/oc8\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"qD7+5690V1lNtCtAaZlS","remoteAddr":"ip","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":1,"time":"2015-08-29T22:38:49+00:00","method":"GET","url":"\/oc8\/owncloud\/index.php\/settings\/apps\/list?category=0&includeUpdateInfo=1"}
{"reqId":"u+YU7xFSK5830yChih4e","remoteAddr":"ip","app":"core","message":"App directory already exists","level":3,"time":"2015-08-29T22:39:04+00:00","method":"POST","url":"\/oc8\/owncloud\/index.php\/settings\/ajax\/enableapp.php"}
{"reqId":"bIg\/Jtz8B2SVCoCL1jts","remoteAddr":"ip","app":"core","message":"App directory already exists","level":3,"time":"2015-08-29T22:39:10+00:00","method":"POST","url":"\/oc8\/owncloud\/index.php\/settings\/ajax\/enableapp.php"}
```

**Comment by karlitschek** [comment] 2015-08-31 08:30
So how have you installed the mail app in the first place? manually or via the apps page?

**Comment by karlitschek** [comment] 2015-08-31 08:30
@DeepDiver1975 FYI

**Comment by tflidd** [comment] 2015-08-31 11:15
I think it was the app store. But I'm not 100% sure, could be as well the release from github. I only moved the folder, is there a way to find out if it is the github-release or the app-version?

**Comment by VicDeo** [comment] 2015-09-04 15:35
@tflidd Is it looks like https://github.com/owncloud/core/issues/16092 ?

**Comment by VicDeo** [comment] 2015-09-04 15:38
Updater doesn't touch apps at all since core has own logic to deal with apps.
Surely none of apps will be deleted by updater.
It's by design.

**Comment by tflidd** [comment] 2015-09-04 16:10
@VicDeo the error seems to be similar to https://github.com/owncloud/core/issues/16092
The error message is not really helping. For other apps, which can be updated, a directory exists as well but it is no problem. So it's more a problem of the app that an update can't be identified or matched to its previous version?

**Comment by VicDeo** [comment] 2015-09-04 16:26
@tflidd OcsId was added on May 9,2015 with this commit https://github.com/owncloud/mail/commit/5c31fffc277464d00473eb9867b536a946dfd549#diff-224bb875c5d3cfcd7621135069013242

If you installed the app before this date it might refuse to update the app due to OcsId mismatch.

This message is thrown as an exception in core 
https://github.com/owncloud/core/blob/6e4a79f8529a69b846f73257cc581d2b80f7762d/lib/private/installer.php#L93  and has nothing to do with updater app.
Updater app update ownCloud itself.

**Comment by tflidd** [comment] 2015-09-04 16:39
It might not be related to the updater app but you won't have this problem on manual upgrades as you delete all folders except config/ and data/.

I kept the old folder from the mail app, and the info.xml shows an ocs-id
````
<?xml version="1.0"?>
<info>
	<id>mail</id>
	<name>Mail</name>
	<description>Easy to use email client which connects to your mail server via IMAP and SMTP.</description>
	<version>0.1.3</version>
	<licence>AGPL</licence>
	<author>Thomas Müller, Jan-Christoph Borchardt, Christoph Wurst, Lukas Reschke, Thomas Imbreckx, Steffen Lindner, Robin McCorkell, Clement Wong &amp; many more …</author>
	<documentation>
		<user>https://github.com/owncloud/mail/wiki</user>
		<admin>https://github.com/owncloud/mail#readme</admin>
	</documentation>
	<dependencies>
		<owncloud min-version="7.0" max-version="8.1" />
		<php min-version="5.4" max-version="5.6" />
	</dependencies>
	<ocsid>169914</ocsid>
</info>
````

**Comment by VicDeo** [comment] 2016-02-16 18:14
Closing as unrelated to updater and a duplicate of the following core issues
https://github.com/owncloud/core/issues/19099
https://github.com/owncloud/core/issues/19690
the latter has reproduction steps that are not connected to Updater
So it's obviously quirks of adding/changing app OCSID or/and different OCSID for the same app_id.
Should be fixed in core.

**Closed by VicDeo** 2016-02-16 18:14 UTC
Labels: bug
