### ISSUE TITLE
updater stuck in maintenance mode / update 8.0.2 -> 8.03

### ISSUE THREAD

**Issue by moritzthecat** [owncloud/updater#129] opened 2015-05-24 09:43 UTC
Although the app looks much improved with the feedback it gives to the steps during update, there is still an issue handling data directories outside of the owncloud directory. 
It might be related to https://github.com/owncloud/updater/issues/73 

Symptom: updater (8.0.2) is stuck in maintenance mode after having reported steps 1 to 3 being complete.

Log file complains about missing data directory, which is right because it is outside of the owncloud directory for security reasons as adviced by owncloud documentation.

LOG: 
[Sun May 24 10:22:46 2015] [error] [client xxx.yyy.zzz.aaa] File does not exist: <path to>/www/myownclouddir/data
[Sun May 24 10:32:42 2015] [error] [client xxx.yyy.zzz.aaa] (70007)The timeout specified has expired: ap_content_length_filter: apr_bucket_read() failed, referer: https://mywebsite/myownclouddir/

Workaround that worked for me
1. create empty data dir in myowncloudddir
2. set maintenance mode manually to false
3. reload https://mywebsite/myownclouddir - restarted and completed the update process

**Comment by VicDeo** [comment] 2015-05-25 14:07
@moritzthecat datadir is not touched by Updater. Most likely you need set this option to false in your `config.php` for this entry to dissapear:
https://github.com/owncloud/core/blob/master/config/config.sample.php#L453

**Comment by VicDeo** [comment] 2015-05-25 14:11
and `maintenance mode` is enabled by core btw. there is nothing to fix from the point of updater

**Comment by VicDeo** [comment] 2015-07-27 15:05
closing due to lack of info. Most likely a duplicate of https://github.com/owncloud/updater/issues/86

**Closed by VicDeo** 2015-07-27 15:05 UTC
