### ISSUE TITLE
Update was unsuccessful

### ISSUE THREAD

**Issue by MrLaziz** [owncloud/updater#116] opened 2015-05-06 09:58 UTC
Hi,

When I try to update from 8.0 to 8.0.3; I got error 
The update was unsuccessful. Please check logs at admin page and report this issue to the ownCloud community.

![screenshot 2015-05-06 13 16 52](https://cloud.githubusercontent.com/assets/1052415/7491460/64204604-f3f2-11e4-8d53-c6c8634d7db1.png)

**Comment by VicDeo** [comment] 2015-05-06 14:58
@MrLaziz please look here for a workaround https://github.com/owncloud/updater/issues/86#issuecomment-99187323

Closing as a duplicate of https://github.com/owncloud/updater/issues/86

**Closed by VicDeo** 2015-05-06 14:58 UTC
Labels: bug
