### ISSUE TITLE
Broken in C 8.2? 

### ISSUE THREAD

**Issue by briskspirit** [owncloud/updater#184] opened 2015-10-20 21:29 UTC
This screenshot will tell more:
![untitled](https://cloud.githubusercontent.com/assets/11968822/10621662/d60df326-778a-11e5-9101-3152901cbc4d.png)

**Comment by nickvergessen** [comment] 2015-10-28 12:33
@VicDeo

**Comment by briskspirit** [comment] 2015-10-28 12:37
Closed, problem gone itself... maybe after disabling asset.pipeline (which fixed "eval" errors and music app)

**Comment by mmattel** [comment] 2015-10-30 08:59
Sorry, we cant close an issue just because a config parameter causes problems and we disable that parameter. The problem has to be fixed. I can confirm that by disabling 
````
'assetdirectory' => '/var/www/owncloud',
'asset-pipeline.enabled' => true,
````
the problem went away. We have to fix issues with the asset settings.

**Comment by mmattel** [comment] 2015-10-30 18:05
@nickvergessen @VicDeo 
The browser (W7/Opera) shows that when using the asset parameter, assets are loaded from that directory.
![image](https://cloud.githubusercontent.com/assets/3321281/10853682/97ac6ebe-7f37-11e5-876e-a474d08d8bc7.png)
Could it be that not all code is aggregated into those asset files and therefore missing to be executed? 
I also have tried playing around (because of nginx) with the location parameter, but there is no difference

**Comment by nickvergessen** [comment] 2015-10-30 23:15
I think the update should ignore the asset stuff and just serve single files

**Comment by mmattel** [comment] 2015-11-11 08:47
Any news on that?

**Comment by kriztan** [comment] 2015-11-11 15:35
I have the same issue:
Some days ago, I've upgraded from OC 8.1 to OC 8.2 like it is described in the docs. After Upgrading everything is working, except the updater. In the admin settings the updater shows:
![image](https://cloud.githubusercontent.com/assets/3350754/11094717/9a970fcc-8891-11e5-9a3e-deb006953b0d.png)

I've looked into the database and searched for the key `lastupdateResult`, the value is `{"version":{},"versionstring":{},"url":{},"web":{}}`

**Comment by nickvergessen** [comment] 2015-11-11 16:50
Your issue is https://github.com/owncloud/core/issues/20251

**Comment by nickvergessen** [comment] 2015-11-13 15:39
Reopening since closing was not intended

**Comment by ggeorgg** [comment] 2015-11-19 23:23
same problem for me. updater app broken like mentioned above.

**Comment by sedrubal** [comment] 2015-12-02 02:05
same problem here and I can confirm, that removing the line `'asset-pipeline.enabled' => true,` from `config/config.php` solves the problem. But it would be very nice if the updater plugin supports pipelining, too.

**Comment by nickvergessen** [comment] 2015-12-02 12:22
@VicDeo any chance?

**Comment by PVince81** [comment] 2015-12-02 12:30
> I think the update should ignore the asset stuff and just serve single files

@VicDeo is this a possible quickfix for 8.2.2 ?

**Comment by nickvergessen** [comment] 2015-12-02 12:48
> I think the update should ignore the asset stuff and just serve single files

I already did that https://github.com/owncloud/core/pull/20461

**Comment by VicDeo** [comment] 2015-12-02 15:50
@PVince81 no. because it is embedded into the admin page

**Comment by VicDeo** [comment] 2015-12-02 15:53
@briskspirit @mmattel @kriztan @ggeorgg 
You are welcome to test https://github.com/owncloud/updater/issues/184

**Comment by VicDeo** [comment] 2015-12-02 15:54
er. I mean #198

**Comment by PVince81** [comment] 2015-12-04 17:18
Fix https://github.com/owncloud/updater/issues/198 was merged.

**Closed by PVince81** 2015-12-04 17:18 UTC
Labels: bug
