### ISSUE TITLE
Updater app does not move/rename __apps/ directory back to apps/ (update via browser)

### ISSUE THREAD

**Issue by mmattel** [owncloud/updater#291] opened 2016-03-22 10:56 UTC
As follow up problem of
owncloud/core#23469
owncloud/updater/issues/290

When running the updater via the browser, the updater moves/renames the apps/ directory to __apps/, but not back. Because there is an empty apps/ directory, the instance behaves dead after upgrading. After manually fixing this (renaming __apps/ to apps/) the instance is back alive again.

**Comment by VicDeo** [comment] 2016-03-22 11:16
@mmattel duplicate of https://github.com/owncloud/updater/issues/280

Fixed with
https://github.com/owncloud/updater/pull/281
https://github.com/owncloud/updater/issues/282

**Closed by VicDeo** 2016-03-22 11:16 UTC

**Comment by mmattel** [comment] 2016-03-22 11:26
Thanks
