### ISSUE TITLE
Error during update from 9.01 (stable) to 9.0.4 - Fatal error: Uncaught exception

### ISSUE THREAD

**Issue by ytodae** [owncloud/updater#385] opened 2016-09-29 15:14 UTC
Hi guys,

i've searched very long for this issue, but i did't find something what helped me. I don't want to install my owncloud for every update new.

Error message after i click the updater (**my version:** ownCloud 9.0.1 (stable))

`Fatal error: Uncaught exception 'Symfony\Component\Process\Exception\ProcessFailedException' with message 'The command "php /homepages/0/XYZPATH/htdocs/owncloud/occ --no-warnings config:list --private --output "json"" failed. Exit Code: 255(Unknown error) Output: ================ X-Powered-By: PHP/4.4.9 Content-type: text/html <br /> <b>Parse error</b>: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in <b>/homepages/0/XYZPATH/htdocs/owncloud/updater/index.php</b> on line <b>23</b><br /> Error Output: ================ ' in /homepages/0/XYZPATH/htdocs/owncloud/updater/src/Utils/OccRunner.php:50 Stack trace: #0 /homepages/0/XYZPATH/htdocs/owncloud/updater/src/Utils/OccRunner.php(56): Owncloud\Updater\Utils\OccRunner->run('--no-warnings c...') #1 /homepages/0/XYZPATH/htdocs/owncloud/updater/src/Utils/ConfigReader.php(106): Owncloud\Updater\Utils\OccRunner->runJson('config:list --p...') #2 /homepages/0/XYZPATH/htdocs/owncloud/updater/src/Utils/ConfigReader.php(50): Own in /homepages/0/XYZPATH/htdocs/owncloud/updater/src/Utils/OccRunner.php on line 50`

Can anyone help me please?

Thanks in advance!

**Comment by VicDeo** [comment] 2016-09-30 21:47
@ytodae Looks like the file `owncloud/updater/index.php` was broken on upload
Does your system pass integrity check?
See https://doc.owncloud.org/server/9.0/admin_manual/issues/code_signing.html for details

**Comment by ytodae** [comment] 2016-10-04 14:13
@VicDeo how can i test the integrity check?
i've installed 9.1.0 (stable) with the webinstaller from the scratch and synched the files from my mac back, but i think i will get this error again (like in the past).

**Comment by VicDeo** [comment] 2016-10-04 14:17
@ytodae the link explains that better than me.
in short: either
`$php occ integrity:check-core`
or
Security & setup warnings section at the admin page

**Comment by ytodae** [comment] 2016-10-04 14:29
@VicDeo this is what i see there:

> **Security & setup warnings**
> You are accessing this site via HTTP. We strongly suggest you configure your server to require using HTTPS instead as described in our security tips.
> No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our documentation.
> Please double check the installation guides ↗, and check for any errors or warnings in the log.

**Comment by VicDeo** [comment] 2016-12-13 22:21
@ytodae Is this still an issue?

**Comment by ytodae** [comment] 2016-12-13 22:33
@VicDeo yes. I don't want to install every new update from scratch. :(

**Comment by VicDeo** [comment] 2016-12-13 22:36
@ytodae ah, you are  on 9.1.0 now. Is the trace the same?

**Comment by VicDeo** [comment] 2016-12-13 22:37
@ytodae  Please start with applying this to your ownCloud
https://central.owncloud.org/t/patches-for-known-update-issues-from-version-9-0-4-9-0-5-9-1-0-9-1-1/3549

**Comment by ytodae** [comment] 2016-12-13 22:41
@VicDeo my Version is right now: ownCloud 9.1.1 (stable)

If i try to start the Updater, i get this message:

> [UnexpectedValueException]
Could not parse a response for config:list. Please check if the current shell user can run occ command. Raw output:
Not allowed
<img width="948" alt="bildschirmfoto 2016-12-13 um 23 40 32" src="https://cloud.githubusercontent.com/assets/22525170/21162430/988ce676-c18d-11e6-8cef-abe55add944d.png">

**Comment by VicDeo** [comment] 2016-12-13 22:42
@ytodae yes, this issue is addressed with the patch by the link above. 
You can download either patch to apply or a package with already patched files.

**Comment by ytodae** [comment] 2016-12-13 22:59
@VicDeo crazy. Thank you very much, it worked like a charm. Will this be fixed for the future releases (e.g. when i install owncloud from scratch on an other server?)

**Comment by VicDeo** [comment] 2016-12-14 14:57
@ytodae this patch is included into updater since 9.0.6 / 9.1.2.
But I can't guarantee that there never will be any bug in future :smile: 
Closing as fixed. 
Feel free to open another issue if you come across with an unexpected behavior.

**Closed by VicDeo** 2016-12-14 14:57 UTC
