### ISSUE TITLE
Issue migration from 8.2.2 to 9.0.0

### ISSUE THREAD

**Issue by nlienard** [owncloud/updater#270] opened 2016-03-09 10:32 UTC
OS: Jessie Debian 8
OwnCloud Version : 8.2.2

Repo:

www-data@tools01:~/owncloud$ cat /etc/apt/sources.list.d/owncloud.list
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /

apt-get upgrade owncloud

+

www-data@tools01:~/owncloud$ ./occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checking whether the database schema for <activity> can be updated (this can take a long time depending on the database size)
Checking whether the database schema for <files_external> can be updated (this can take a long time depending on the database size)
Checking whether the database schema for <files_sharing> can be updated (this can take a long time depending on the database size)
Checking whether the database schema for <files_trashbin> can be updated (this can take a long time depending on the database size)
Checking whether the database schema for <notifications> can be updated (this can take a long time depending on the database size)
Checking whether the database schema for <user_ldap> can be updated (this can take a long time depending on the database size)
Checked database schema update for apps
Updating database schema
Updated database
Disabled 3rd-party app: announcementcenter
Disabled incompatible app: calendar
Disabled 3rd-party app: calendar
Disabled 3rd-party app: collaboration
Disabled incompatible app: contacts
Disabled 3rd-party app: contacts
Disabled incompatible app: documents
Disabled 3rd-party app: documents
Disabled 3rd-party app: files_drawio
Disabled 3rd-party app: files_videoviewer
Disabled 3rd-party app: files_w2g
Disabled 3rd-party app: libreonline
Disabled 3rd-party app: mail
Disabled 3rd-party app: news
Disabled 3rd-party app: notes
Disabled 3rd-party app: ojsxc
Disabled 3rd-party app: tasks
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 0.8
Updating <files_texteditor> ...
Updated <files_texteditor> to 2.1
Updating <gallery> ...
Updated <gallery> to 14.5.0
Updating <user_ldap> ...
Updated <user_ldap> to 0.8.0
Updating <files> ...
Updated <files> to 1.4.4
Updating <activity> ...
Updated <activity> to 2.2.1
Updating <files_external> ...
Updated <files_external> to 0.5.2
Updating <files_sharing> ...
Updated <files_sharing> to 0.9.1
Updating <files_trashbin> ...
Updated <files_trashbin> to 0.8.0
Updating <files_versions> ...
Updated <files_versions> to 1.2.0
Updating <notifications> ...
Updated <notifications> to 0.2.3
Updating <provisioning_api> ...
Updated <provisioning_api> to 0.4.1
Update 3rd-party app: calendar
Update 3rd-party app: collaboration
Update 3rd-party app: contacts
Update 3rd-party app: documents
Update 3rd-party app: files_w2g
Update 3rd-party app: mail
Update 3rd-party app: news
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Reset log level
www-data@tools01:~/owncloud$ .

then all fails after that : 

www-data@tools01:~/owncloud$ php updater/application.php upgrade:checkpoint -h
PHP Warning:  include(/var/www/version.php): failed to open stream: No such file or directory in /var/www/owncloud/updater/src/Utils/Locator.php on line 182
PHP Warning:  include(): Failed opening '/var/www/version.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/owncloud/updater/src/Utils/Locator.php on line 182
PHP Notice:  Undefined variable: OC_Version in /var/www/owncloud/updater/src/Utils/Locator.php on line 185
PHP Warning:  implode(): Invalid arguments passed in /var/www/owncloud/updater/src/Console/Application.php on line 148

  [RuntimeException]
  Minimum ownCloud version 9.0.0 is required for the updater -  was found in /var/www

www-data@tools01:~/owncloud$ curl http://localhost/owncloud/
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /var/www/owncloud/index.php was not found on this server.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at localhost Port 80</address>
</body></html>
www-data@tools01:~/owncloud$

www-data@tools01:~/owncloud$ ls -la  /var/www/owncloud/index.php
-rw-r--r-- 1 www-data root 2026 Mar  8 14:54 /var/www/owncloud/index.php

what 's wrong ?

thanks

**Comment by nlienard** [comment] 2016-03-09 10:33
www-data@tools01:~/owncloud$ ./occ status
  - installed: true
  - version: 9.0.0.19
  - versionstring: 9.0.0
  - edition:

**Comment by LukasReschke** [comment] 2016-03-09 10:34
> www-data@tools01:~/owncloud$ php updater/application.php upgrade:checkpoint -h
PHP Warning: include(/var/www/version.php): failed to open stream: No such file or directory in /var/www/owncloud/updater/src/Utils/Locator.php on line 182

Seems to read the wrong file cc @VicDeo

**Comment by nlienard** [comment] 2016-03-09 10:35
this one is ok:

www-data@tools01:~/owncloud$ ./occ app:list
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - announcementcenter
  - calendar
  - collaboration
  - contacts
  - documents
  - encryption
  - files_drawio
  - files_w2g
  - libreonline
  - mail
  - news
  - notes
  - ojsxc
  - tasks
  - tasks_enhanced
  - user_external
www-data@tools01:~/owncloud$

**Comment by nlienard** [comment] 2016-03-09 10:43
http://localhost/owncloud/ <= not working
http://localhost/owncloud/index.php <= working

+ on page after login:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- depot/166206-files_drawio.zip

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [depot/166206-files_drawio.zip] => Array
                        (
                            [expected] => 
                            [current] => f61cb85fe4f8ffc2fb852ebe0d13d02ed38674cf693b73c29acb6bb4b64512af5bbea5157fcef42d90182bddaf5964b83917a0e16e6b4846ebcd50d34b45bece
                        )

                )

        )

)

**Comment by evilJazz** [comment] 2016-03-09 13:57
Same problem here. It looks like the .htaccess in /var/www/owncloud has new rewrite rules which cause the issue. Adding 
RewriteCond %{REQUEST_URI} !^/owncloud/$
right before
RewriteRule .* index.php [PT,E=PATH_INFO:$1]
in the # Rewrite rules for `front_controller_active` block works around the issue. Not perfect though.

**Comment by VicDeo** [comment] 2016-03-09 15:41
@evilJazz  Do you have another `.htaccess` in the directory above `/owncloud`?

**Comment by evilJazz** [comment] 2016-03-09 15:46
@VicDeo No, no other .htaccess. This is a stock installation of the Debian 8.x packages. Just the default unmodified /etc/apache2/conf-enabled/owncloud.conf

**Comment by PVince81** [comment] 2016-03-09 15:48
Okay, so you guys were all using distro packages, not the updater app.

@jnweiger for packaging

**Comment by VicDeo** [comment] 2016-03-09 16:14
@nlienard 
```
www-data@tools01:~/owncloud$ php updater/application.php upgrade:checkpoint -h
PHP Warning: include(/var/www/version.php): failed to open stream: No such file or directory in 
```
is addressed in https://github.com/owncloud/updater/pull/271

@PVince81 @evilJazz 
http://localhost/owncloud/ <= not working
http://localhost/owncloud/index.php <= working
Duplicate of  https://github.com/owncloud/core/issues/22970
Let's track one issue per report ;)

**Comment by PVince81** [comment] 2016-03-09 17:41
@VicDeo assigning to you for now. If you think it's a packaging issue, reassign to @jnweiger. Thanks

**Comment by VicDeo** [comment] 2016-03-09 18:09
@PVince81 correct, I'll take the first from the list above, the second belongs to core

**Comment by nlienard** [comment] 2016-03-09 20:52
thanks 
(about issue 2; with htaccess, i received some help on IRC sporting me to comment the rewrite rule so now it works for this part).

**Comment by VicDeo** [comment] 2016-03-09 20:56
@nlienard can you also confirm that changes from https://github.com/owncloud/updater/pull/271/files
fixes the issue with `php updater/application.php upgrade:checkpoint -h`?

**Comment by nlienard** [comment] 2016-03-10 08:26
After applying the patch, it works well:

www-data@tools01:~/owncloud$ php updater/application.php upgrade:checkpoint -h
Usage:
  upgrade:checkpoint [options]

Options:
      --create           create a checkpoint
      --restore=RESTORE  revert files to a given checkpoint
      --list[=LIST]      show all checkpoints
  -h, --help             Display this help message
  -q, --quiet            Do not output any message
  -V, --version          Display this application version
      --ansi             Force ANSI output
      --no-ansi          Disable ANSI output
  -n, --no-interaction   Do not ask any interactive question
  -v|vv|vvv, --verbose   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
 Create or restore owncloud core files

**Comment by VicDeo** [comment] 2016-03-10 14:29
@nlienard the second issue should be fixed with https://github.com/owncloud/core/pull/23029

**Comment by VicDeo** [comment] 2016-03-10 14:37
Fix is merged to master/stable9

**Closed by VicDeo** 2016-03-10 14:37 UTC
Labels: bug, sev2-high

**Comment by VicDeo** [comment] 2016-03-10 14:47
>http://localhost/owncloud/ <= not working
http://localhost/owncloud/index.php <= working

Another duplicate in core with a solution is https://github.com/owncloud/core/issues/23098
Unrelated to updater anyway

**Comment by nazar-pc** [comment] 2016-04-13 08:03
I've got this issue today as well during update from 8.2.3 to 9.0.1: https://github.com/owncloud/core/issues/22151#issuecomment-209203802
