### ISSUE TITLE
Cannot update the server: extraction error

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/updater#128] opened 2015-05-22 12:00 UTC
I've modify the code a bit to download the package from a local server (in fact it's the same server where ownCloud is installed). The "target" package to download is the daily build
```
$OC_Version = array(8,1,0,6);
$OC_VersionString = '8.1 beta 2';
$OC_Channel = 'daily';
$OC_Build = '2015-05-21T03:31:21+00:00 d560d1ef2a106bb7e89907a4004ef371cc4ddc4a';
```

The info returned by the mock update.php (the endpoint where the app connects) is
```
<?xml version="1.0"?>
 <owncloud>
   <version>8.1.9.9</version>
   <versionstring>ownCloud 8.1.9 ultimate edition</versionstring>
   <url>http://10.40.30.21:8181/oc-ultimate-package.tar.bz2</url>
   <web>http://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.h    tml</web>
 </owncloud>
```

At this point, the updater app detects a new version, and downloads the version correctly. However there is an extraction error that prevents the installation.

```
{"reqId":"atN462K8sDQDZcuthJva","remoteAddr":"10.40.30.21","app":"updater","message":"Use already downloaded package \/home\/jvillafanez\/src\/owncloud\/owncloud-oc8.1\/data\/updater_backup\/8.1.9.9.tar.bz2. Size is 24882969 bytes.","level":0,"time":"2015-05-22T11:34:39+00:00","method":"POST","url":"\/index.php\/apps\/updater\/ajax\/download.php"}
{"reqId":"atN462K8sDQDZcuthJva","remoteAddr":"10.40.30.21","app":"updater","message":"Retrieving http:\/\/10.40.30.21:8181\/oc-ultimate-package.tar.bz2","level":3,"time":"2015-05-22T11:34:39+00:00","method":"POST","url":"\/index.php\/apps\/updater\/ajax\/download.php"}
{"reqId":"atN462K8sDQDZcuthJva","remoteAddr":"10.40.30.21","app":"updater","message":"\/home\/jvillafanez\/src\/owncloud\/owncloud-oc8.1\/data\/updater_backup\/8.1.9.9.tar.bz2 extraction error","level":3,"time":"2015-05-22T11:34:39+00:00","method":"POST","url":"\/index.php\/apps\/updater\/ajax\/download.php"}
```

What I understand is that the package should be extracted, regardless of any other possible extra check such as the version matching between 8.1.9.9 and the real one 8.1.0.6.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 2

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by cmonteroluque** [comment] 2015-05-22 12:12
@VicDeo can you please have a look?

**Comment by VicDeo** [comment] 2015-05-22 14:38
@jvillafanez core failure. https://github.com/owncloud/updater/blob/master/lib/downloader.php#L49

**Comment by VicDeo** [comment] 2015-05-22 14:51
Nothing in OC_Archive indicates that there is a failure. Actually this condition have never worked
https://github.com/owncloud/updater/blob/master/lib/downloader.php#L50
and the only thing I can do is to check whether anything is created by OC_Archive while unpacking the package here https://github.com/owncloud/updater/blob/master/lib/downloader.php#L63

**Comment by jvillafanez** [comment] 2015-05-25 06:49
@DeepDiver1975 @PVince81 could you check the failure in the OC_Archive class?

**Comment by PVince81** [comment] 2015-05-26 08:09
@VicDeo can you take care of this as you might have a better understanding of the context. Thanks.
Let me know if you still need help digging into this class (which I'm not familiar with either)

**Comment by VicDeo** [comment] 2015-06-04 21:14
hm. originating from 3rdparty
>When the extraction is aborted, a PEAR error text is set and false
     * is returned. However the result can be a partial extraction that may
     * need to be manually cleaned.

https://github.com/owncloud/3rdparty/blob/master/pear/archive_tar/Archive/Tar.php#L553

**Comment by cmonteroluque** [comment] 2015-06-25 21:14
to 8.2, may require an update of a 3rd party component

**Comment by VicDeo** [comment] 2015-10-13 18:46
@jvillafanez 
a) does `oc-ultimate-package.tar.bz2` has `owncloud` root folder inside?
b) for bz2 support you need https://github.com/owncloud/core/pull/19182

**Comment by jvillafanez** [comment] 2015-10-14 06:59
@VicDeo I guess it should. The package was renamed from one of the official ownCloud daily packages.

**Comment by VicDeo** [comment] 2016-02-16 18:53
Details on tar.bz2 core support https://github.com/owncloud/updater/issues/188#issuecomment-159019744

**Comment by VicDeo** [comment] 2016-02-16 18:58
closing as a duplicate of https://github.com/owncloud/core/issues/18880
since before 9.0 core libraries are used to work with packages

**Closed by VicDeo** 2016-02-16 18:58 UTC
Labels: bug
